### ISSUE TITLE
Camp needs to indicate it was a 2019 event

### ISSUE THREAD

**Issue by daviddias** [ipfs/camp.ipfs.io#37]
From @whyrusleeping report:
<img width="635" alt="image" src="https://user-images.githubusercontent.com/1211152/67209837-6147d200-f418-11e9-8138-d8132158bbff.png">

@cwaring can you push a fix for this?

**Comment by cwaring** [comment]
Good call, I think we should archive this to a different url to make it obvious too.

Something like:
`2019.camp.ipfs.io`

Then it's easier to boot up a new one for future years if required. Although I'd prefer to have the year in the url from the beginning of the project so that we don't break inbound links with future migrations. eg, `2020.camp.ipfs.io`

**Comment by cwaring** [comment]
`camp.ipfs.io` could always redirect to the latest edition as a shortcut url.

**Comment by daviddias** [comment]
Why not `https://camp.ipfs.io/2019` instead? Seems to be the practice among conferences and it is only one DNS record to maintain and also easier to cache it from the IPFS side (given that it is served by IPFS).

**Comment by daviddias** [comment]
Oh right, the site is broken when loaded on a relative path https://github.com/ipfs/camp.ipfs.io/issues/4, understand now why the preference of 2019.camp.ipfs.io vs camp.ipfs.io/2019

**Comment by cwaring** [comment]
Most conferences tend to lean toward `year.name.ext` for similar reasons of isolating old code and separating deployment concerns. Many don't even bother and just replace the primary site each year. https://websummit.com/ being a prime example there 😅

**Comment by cwaring** [comment]
In the meantime I'll patch the current site so that the year is included next to any dates.
